### PR TITLE
PR - 53450 - Update filters for AATF's and PCS's (EXTERNAL)

### PR DESCRIPTION
**Pull request by meglenapnovoselska**

### CODE REVIEW

**Comment by JohnPadgettCivica** [comment]
@meglenapnovoselska Looks fine... are you able to push a minor change to the branch so that we can see if it builds ok

**Comment by meglenapnovoselska** [comment]
> @meglenapnovoselska Looks fine... are you able to push a minor change to the branch so that we can see if it builds ok

sure

**Comment by JohnPadgettCivica** [comment]
@meglenapnovoselska Looks like there is a compilation warning

image

**Comment by meglenapnovoselska** [comment]
> @meglenapnovoselska Looks like there is a compilation warning
> 
> image

okay, i will have a look

**Pull request merged**
